drop table if exists player_domain CASCADE;
drop table if exists team_domain CASCADE;
create table player_domain (playerid bigint generated by default as identity, player_name varchar(255) not null, playerign varchar(255) not null, team_teamid bigint, primary key (playerid));
create table team_domain (teamid bigint generated by default as identity, team_name varchar(255) not null, primary key (teamid));

